// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4TkVVEP9jwX8Sne4SgtbxHhok9Zvj1KM',
    appId: '1:298650638052:web:7c9eb6fc78bf0a9a117ef1',
    messagingSenderId: '298650638052',
    projectId: 'carelink-ed6ff',
    authDomain: 'carelink-ed6ff.firebaseapp.com',
    databaseURL: 'https://carelink-ed6ff-default-rtdb.firebaseio.com',
    storageBucket: 'carelink-ed6ff.firebasestorage.app',
    measurementId: 'G-Y33K9HFNE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOSDAV9eXjW7pqYpKJPyf6ENlpRaq61gE',
    appId: '1:298650638052:android:4f31fc0f4cec54b6117ef1',
    messagingSenderId: '298650638052',
    projectId: 'carelink-ed6ff',
    databaseURL: 'https://carelink-ed6ff-default-rtdb.firebaseio.com',
    storageBucket: 'carelink-ed6ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4om603WCGPtDjXVoddgVkYPf-L6ve2SA',
    appId: '1:298650638052:ios:28827ccd2b1de7cb117ef1',
    messagingSenderId: '298650638052',
    projectId: 'carelink-ed6ff',
    databaseURL: 'https://carelink-ed6ff-default-rtdb.firebaseio.com',
    storageBucket: 'carelink-ed6ff.firebasestorage.app',
    iosBundleId: 'com.carelink.carelinkGuardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4om603WCGPtDjXVoddgVkYPf-L6ve2SA',
    appId: '1:298650638052:ios:28827ccd2b1de7cb117ef1',
    messagingSenderId: '298650638052',
    projectId: 'carelink-ed6ff',
    databaseURL: 'https://carelink-ed6ff-default-rtdb.firebaseio.com',
    storageBucket: 'carelink-ed6ff.firebasestorage.app',
    iosBundleId: 'com.carelink.carelinkGuardian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4TkVVEP9jwX8Sne4SgtbxHhok9Zvj1KM',
    appId: '1:298650638052:web:4d76c4bd5157db33117ef1',
    messagingSenderId: '298650638052',
    projectId: 'carelink-ed6ff',
    authDomain: 'carelink-ed6ff.firebaseapp.com',
    databaseURL: 'https://carelink-ed6ff-default-rtdb.firebaseio.com',
    storageBucket: 'carelink-ed6ff.firebasestorage.app',
    measurementId: 'G-9MYT31GYX3',
  );
}
